export const INITIAL_PATH = '/start';
export const ROOT_PATH = '/';

export const NETWORK_REQUEST = 'NETWORK::REQUEST';
export const NETWORK_REQUEST_SUCCESSFUL = 'NETWORK::REQUEST_SUCCESSFUL';
export const NETWORK_REQUEST_FAILED = 'NETWORK::REQUEST_FAILED';

export const SHOW_MODAL_WINDOW = 'MODAL_WINDOW::SHOW';
export const CLOSE_MODAL_WINDOW = 'MODAL_WINDOW::CLOSE';

export const APP_DISCONNECT = 'CONFIG::DESTROY';
export const SET_APP_CONFIG_PATH = 'CONFIG::PATH_SAVED';
export const APP_CONFIG_REQUEST_SUCCESSFUL = 'CONFIG::REQUEST_SUCCESSFUL';
export const APP_CONFIG_REQUEST_FAILED = 'CONFIG::REQUEST_FAILED';

export const CLOSE_ERROR_MESSAGE = 'ERROR_MESSAGE::CLOSE';
export const SET_AUTHENTICATION_DATA = 'SET_AUTHENTICATION_DATA';

export const CACHE_HTTP_PARAMS = 'CACHE_HTTP_PARAMS';
